spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/healbits
    driver-class-name: org.mariadb.jdbc.Driver
    username: healbits_user
    password: h1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa



